### ISSUE TITLE
Implement command getKey

### ISSUE THREAD

**Issue by MangyCoyote** [SRE-PRG/azmitool#101]

**Comment by iricigor** [comment]
Please go above 100 tests in integration also!

**Comment by MangyCoyote** [comment]
https://docs.microsoft.com/en-us/azure/key-vault/keys/about-keys
Key Vault doesn't support EXPORT operations. Once a key is provisioned in the system, it cannot be extracted or its key material modified.

KeyVault gives you only public part. Possibly we can explore "backup" solution, but sounds hacky.
Private part never leaves KeyVault in my opinion (which I think is good) and you "just" somehow refer to a propriate key in a code should you need to encrypt/decrypt ...

No reason to implement "download public part", therefore closing the issue.
