### ISSUE TITLE
Feature request: multiple --exclude parameters

### ISSUE THREAD

**Issue by maksiml2014** [SRE-PRG/azmitool#114]
It would be nice to be able to pass multiple --exclude parameters like `--exclude "*.partial" --exclude "*.haspx"` instead of coming up with tricky regexp.

**Comment by iricigor** [comment]
Document in documentation how to do this with current functionality. Briefly, just use pipe in between two regexes.

Instead of this
`--exclude "*.partial" --exclude "*.haspx"`
use this
`--exclude "*.partial|*.haspx"`

**Comment by iricigor** [comment]
For this we need first to add new property to our options: `arity`
https://github.com/dotnet/command-line-api/wiki/How-To#argument-validation-and-binding

It can be implemented after we add unit testing #149

**Comment by iricigor** [comment]
Feature added in scope of PR #180 and will be released in version 0.5, #172, hopefully within days.
