### ISSUE TITLE
Implement output arguments for getsecret and getcertificate

### ISSUE THREAD

**Issue by iricigor** [SRE-PRG/azmitool#130]
So far we spoke about `--file` and if not there, just use stdout.

Optionally, check also about option to use `--variable`

**Comment by MangyCoyote** [comment]
Variable would me most likely set only for current process (`azmi` itself not a shell above).

**Comment by iricigor** [comment]
What about [environment variables](https://docs.microsoft.com/en-us/dotnet/api/system.environment.setenvironmentvariable?view=netcore-3.1)?

**Comment by MangyCoyote** [comment]
Right, either get/set in current process or Windows Registry (cross-platform!).
