### ISSUE TITLE
support custom MSI

### ISSUE THREAD

**Issue by iricigor** [SRE-PRG/azmitool#16]
Currently tool is using only default MSI, which is fine if VM has only one. If there are more, we should add parameter to select which MSI to use.

**Comment by urtabajev** [comment]
Maybe there could be possibility to set MSI through environment variable too.

**Comment by MangyCoyote** [comment]
![image](https://user-images.githubusercontent.com/43244941/73847346-5d548a00-4826-11ea-9e0c-3f4b202c0cea.png)
Add --identity $string

Application ID = Client ID.

**Comment by iricigor** [comment]
Testing commands sent via email
