### ISSUE TITLE
Confusing error message when vm has more than one user-assigned identities

### ISSUE THREAD

**Issue by urtabajev** [SRE-PRG/azmitool#18]
When virtual machine has two on more user-assigned managed identities then azmitool setblob fails with confusing error message: "General Error: The authentication request failed due to an unhandled exception.  See inner exception for details."

Exception catching in azmi-commandline.cs should not be so generic and provide more meaningful information by exception.

**Comment by iricigor** [comment]
the error should be fixed with #16 , but general exception catching problem will remain

**Comment by urtabajev** [comment]
Same time it should report about multiple possible Managed Service Identities, indeed.
