### ISSUE TITLE
Missing --help option [for subcommands]

### ISSUE THREAD

**Issue by MangyCoyote** [SRE-PRG/azmitool#41]
azmi:
  Command-line utility azmi stands for Azure Managed Identity. It is helping
  admins simplify common operations (reading and writing) on Azure resources.
  It is utilizing Azure AD authentication via user assigned managed identity.

Usage:
  azmi [options] [command]

Options:
  --version    Display version information

Commands:
  gettoken    Obtain Azure authorization token.
  getblob     Downloads storage account blob to local file.
  setblob     Write local file to storage account blob.

**Comment by iricigor** [comment]
This is actually a missing feature (or a bug) inside command-line parser. It looks like the only option for main command is `--version`, while you can use also `--help`.

Also, for commands, you cannot see actual structure or that those support also `--help`.

It will be implemented as additional lines in description for root command and subcommands.
