### ISSUE TITLE
Out of curiosity: compare performance of azmi with e.g. curl 

### ISSUE THREAD

**Issue by MangyCoyote** [SRE-PRG/azmitool#67]

**Comment by iricigor** [comment]
Download tests show slower start (+0.7sec), but faster download operation (22%) for `azmi` vs. `curl`

small file download (<1KB), 100 repeats
azmi 1.01 sec
curl 0.32 sec

large file download (150MB), 10 repeats
curl 15.77 sec
azmi 13.61 sec

**Comment by iricigor** [comment]
Download 1000 small files with `azmi` would last about 17 minutes, while with `curl` it would be about 5 minutes.

**Comment by iricigor** [comment]
Do we want to add this comment somewhere, for example Commands overview page?

**Comment by MangyCoyote** [comment]
If you could re-run perf. test (1 000 small files) using new `getblobs`, that will show us more real stats and note it somewhere e.g. as you suggest to 'Commands' overview page.
There is an idea to improve performance for batches (like e.g. getblobs) see #118 . So maybe you can make a short note about it there as well.

**Comment by iricigor** [comment]
Check also performance of `rclone` vs `getblobs`

**Comment by iricigor** [comment]
[New ADO pipeline](https://dev.azure.com/iiric/azmi/_build?definitionId=29&_a=summary) created for permanent performance testing. Feel free to run it as needed.

Here are results from [current run](https://dev.azure.com/iiric/azmi/_build/results?buildId=1358&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=a46d8783-b972-547c-42b9-2f94289d3941).

**startup tests**
- `azmi --help` 0.8 sec
- `azmi gettoken` - 1.2 sec

**download 1 KB file**
- `azmi getblob` - 2.0 sec
- `azmi v.0.2 getblob`  - 1.9 sec
- `curl` - 0.14 sec _(14x faster)_

**download 70 MB file**
- `azmi getblob` - 3.5 sec
- `azmi v.0.2 getblob`  - 4.8 sec
- `curl` - 1.7 sec _(2x faster)_

**list and download ~1000 files in total 19MB**
- `azmi listblobs` - 0.22 sec
- `rclone ls` - 0.06 sec _(3.5x faster)_
- `azmi getblobs` - 90 sec
- `rclone copy` - 2.3 sec _(40x faster)_

**Comment by iricigor** [comment]
Here are results from [run on Azure F2 sized VM](https://dev.azure.com/iiric/azmi/_build/results?buildId=1365&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=c623b9f5-4e91-5154-177e-19d7203ddd0d). 

**startup tests**
- `azmi --help` 0.03 sec
- `azmi gettoken` - 0.03 sec

**download 1 KB file**
- `azmi getblob` - 0.05 sec
- `azmi v.0.2 getblob`  - 0.05 sec
- `curl` - 0.06 sec

**download 70 MB file**
- `azmi getblob` - 0.17 sec
- `azmi v.0.2 getblob`  - 0.15 sec
- `curl` - 1.1 sec _(6x slower)_

**list and download ~1000 files in total 19MB**
- `azmi listblobs` - 0.6 sec
- `rclone ls` - 0.3 sec _(2x faster)_
- `azmi getblobs` - 90 sec
- `rclone copy` - 0.14 sec _(400x faster)_
