### ISSUE TITLE
Secrets from KeyVault and templating 

### ISSUE THREAD

**Issue by MangyCoyote** [SRE-PRG/azmitool#80]
Blob storage contains a file with placeholders of secrets. Secrets are fetched from keyvault and replaced in the file.

e.g.
```
Some plain text and then comes secret: ${SECRETNAME1}
More secrets: ${SECRETNAME2}
```

**Comment by MangyCoyote** [comment]
Related to #75 .

**Comment by iricigor** [comment]
Native commands will not implement such specific tasks at the moment, as it can be subject to big number of customizations.
Please see examples in documentation ([direct link](https://github.com/SRE-PRG/azmitool/blob/master/Examples.md#example-1)) how this can be achieved using current functionality.
