### ISSUE TITLE
Implement subcommand setBlobs #4

### ISSUE THREAD

**Issue by MangyCoyote** [SRE-PRG/azmitool#88]
```
setBlobs
--container <str>
--directory <str> (huh /home/atlas/../golem/hello.txt how it should behave?)
--force <bool>
--exclude <str>
```

**Comment by iricigor** [comment]
Regarding question: `--directory <str> (huh /home/atlas/../golem/hello.txt` how it should behave?

It will take just directory part and enumerate files from it, therefore `/home/atlas/../golem/` will be the same as `/home/golem/`.
